### ISSUE TITLE
Date format documentation

### ISSUE THREAD

**Issue by jvanz** [okfn-brasil/querido-diario-api#20]
One of the first beta testers told us that the date format used in the API is not clear in the documentation. So, let's check if we can improve that making this info more clear.

**Comment by dbg-certi** [comment]
OK. I'll try to improve the date part and send to you a draft with the modifications. Sorry for the late answer but I didn't receive any notification from github.

**Comment by GeraAlcantara** [comment]
Can I work on This ?

**Comment by jvanz** [comment]
Sure!

**Comment by GeraAlcantara** [comment]
I did have problems with podman since im working on a windos machin and normaly I use docker-compose
But I did't need to run de aplication to made the changes since I now where the description fields are locate on de routes 
I add de that format to be easy to see Year-Month-Day and remove the long description in the input field since is not doesn't help how the data is expected (correct format) 

I hope you like the approach

Happy coding and happy Hacktoberfest

**Comment by GeraAlcantara** [comment]
PR #44

**Comment by jvanz** [comment]
PR merged. Closing issue...
